# Deploys MongoDB with customization scripts and container with Mongo client
# https://fabianlee.org/2018/05/20/docker-using-docker-compose-to-link-a-mongodb-server-and-client/
#
# usage:
# sudo docker-compose build
# sudo docker-compose up

services:
  ara-mongodb:
    image: mongo:5.0.28-focal
    container_name: ara-mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=ara
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      # seeding scripts
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - ara_mongodb5:/data/db
      - ara_mongoconfig5:/data/configdb
    networks:
      - mongo_net

volumes:
  # default dir on Ubuntu: /var/lib/docker/volumes
  ara_mongodb5:
  ara_mongoconfig5:

networks:
  mongo_net:
    driver: bridge